rules:
  - group: People Information
    rule:
      - name: Email
        loaded: true
        f_regex: (([a-z0-9]+[_|\.])*[a-z0-9]+@([a-z0-9]+[-|_|\.])*[a-z0-9]+\.[a-z]{2,5})
        sensitive: false
        ignore_case: true
        context_left: 0
        context_right: 0
      - name: Chinese IDCard
        loaded: true
        f_regex: '[^0-9]((\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(\d{6}(18|19|20)\d{2}(0[1-9]|10|11|12)([0-2]\d|30|31)\d{3}(\d|X|x)))[^0-9]'
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: Chinese Mobile Number
        loaded: true
        f_regex: '[^\w]((?:(?:\+|0{0,2})86)?1(?:(?:3[\d])|(?:4[5-79])|(?:5[0-35-9])|(?:6[5-7])|(?:7[0-8])|(?:8[\d])|(?:9[189]))\d{8})[^\w]'
        sensitive: false
        ignore_case: true
        context_left: 0
        context_right: 0
  - group: System Information
    rule:
      - name: Internal IP Address
        loaded: true
        f_regex: '[^0-9]((127\.0\.0\.1)|(10\.\d{1,3}\.\d{1,3}\.\d{1,3})|(172\.((1[6-9])|(2\d)|(3[01]))\.\d{1,3}\.\d{1,3})|(192\.168\.\d{1,3}\.\d{1,3}))'
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: MAC Address
        loaded: true
        f_regex: (^([a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5})|[^a-zA-Z0-9]([a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}))
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: Windows File/Dir Path
        loaded: true
        f_regex: '[^\w]([a-zA-Z]:\\\\?(?:[^<>:/\\|?*]+\\\\?)*)([^<>:/\\|?*]+(?:\.[^<>:/\\|?*]+)?)'
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: JDBC Connection
        loaded: true
        f_regex: (jdbc:[a-z:]+://[a-z0-9\.\-_:;=/@?,&]+)
        sensitive: false
        ignore_case: true
        context_left: 0
        context_right: 0
      - name: Authorization Header
        loaded: true
        f_regex: ((basic [a-z0-9=:_\+\/-]{5,100})|(bearer [a-z0-9_.=:_\+\/-]{5,100}))
        sensitive: false
        ignore_case: true
        context_left: 0
        context_right: 0
  - group: Sensitive Information
    rule:
      - name: Cloud Key
        loaded: true
        f_regex: (((access)(|-|_)(key)(|-|_)(id|secret))|(LTAI[a-z0-9]{12,20}))
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: Password Field
        loaded: true
        f_regex: '((|\\)(|''|")(|[\w]{1,10})(password|passwd|pwd|pass)(|[\.\w]{1,10})(|\\)(|''|")(|)(:|=|!=|[\)]{0,1}\.val\()( |)(|\\)(''|")([^''"]+?)(|\\)(''|")(|,|\)))|((|\\)(''|")([^''"]+?)(|\\)(''|")(|\\)(|''|")(|)(:|[=]{1,3}|![=]{1,2})( |)(|[\.\w]{1,10})(password|passwd|pwd|pass)(|[\.\w]{1,10})(|\\)(|''|"))'
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
      - name: API Key
        loaded: true
        f_regex: '((api|key|token|secret|auth)[\w\-_]*[\s]*[:=][\s]*[''"]?[a-zA-Z0-9\-_]{16,}[''"]?)'
        sensitive: true
        ignore_case: true
        context_left: 50
        context_right: 50
