rules:
  - group: Sensitive Information
    rule:
      - name: Cloud Key
        loaded: true
        f_regex: (((access)(|-|_)(key)(|-|_)(id|secret))|(LTAI[a-z0-9]{12,20}))
        sensitive: true
        context_left: 50
        context_right: 50
      - name: Password Field
        loaded: false
        f_regex: '((|\\)(|''|")(|[\w]{1,10})(password|passwd|pwd|pass)(|[\.\w]{1,10})(|\\)(|''|")(|)(:|=|!=|[\)]{0,1}\.val\()( |)(|\\)(''|")([^''"]+?)(|\\)(''|")(|,|\)))|((|\\)(''|")([^''"]+?)(|\\)(''|")(|\\)(|''|")(|)(:|[=]{1,3}|![=]{1,2})( |)(|[\.\w]{1,10})(password|passwd|pwd|pass)(|[\.\w]{1,10})(|\\)(|''|"))'
        sensitive: true
        context_left: 50
        context_right: 50
      - name: API Key
        loaded: true
        f_regex: '((api|key|token|secret|auth)[\w\-_]*[\s]*[:=][\s]*[''"]?[a-zA-Z0-9\-_]{16,}[''"]?)'
        sensitive: true
        context_left: 50
        context_right: 50
